// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ofvrujqjbqevpalfzoyh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9mdnJ1anFqYnFldnBhbGZ6b3loIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEwMDkwMjksImV4cCI6MjA2NjU4NTAyOX0.lYqjpWhiNLR6ATmXgxvcU7lpAZxCAOOSrT-c79_vESQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);